# Generated by Django 4.1.1 on 2022-10-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='created_at',
        ),
    ]
