# Generated by Django 4.1.1 on 2022-10-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_institution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Dollar_Sign.svg/500px-Dollar_Sign.svg.png?20120706173622', max_length=500),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=250)),
                ('balance_available', models.IntegerField(default=0)),
                ('balance_current', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=250)),
                ('account_subtype', models.CharField(max_length=250)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='main_app.institution')),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
    ]
