# Generated by Django 4.1.1 on 2022-10-03 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_institution_logo_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('sub_category', models.CharField(default='', max_length=250)),
                ('sub_sub_category', models.CharField(default='', max_length=250)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_id', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('credited_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='main_app.account')),
                ('debited_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='main_app.account')),
            ],
            options={
                'ordering': ['transaction_id'],
            },
        ),
    ]
