# Generated by Django 4.1.2 on 2022-10-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_account_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('transactions', models.ManyToManyField(to='main_app.transaction')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
