# Generated by Django 4.1.2 on 2022-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='transactions',
            field=models.ManyToManyField(default='', to='main_app.transaction'),
        ),
    ]
